name: Metrics
on:
  schedule: [{cron: "0 */8 * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GH_TOKEN }}
          config_timezone: Europe/Paris

          plugin_lines: yes

          plugin_traffic: yes

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          
          

          plugin_habits: yes
          plugin_habits_charts: yes

          plugin_languages: yes

          plugin_followup: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1 # Display #1 project of lowlighter/metrics repository
          plugin_projects_limit: 4                                    # Limit to 4 entries
          plugin_projects_descriptions: yes    
