name: Update GitHub Profile README
on:
  push:
  schedule:
    - cron: "*/15 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update GitHub Profile README
      uses: jumalley/github-update-readme@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: "👋"
        subhead: ""
        footer: ""
        ref: "main"
        excludeActivity: ''
        excludeRepo: ''
